services:

  postgres:
    image: postgres:latest
    container_name: main-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-payment:
    image: postgres:latest
    container_name: payment-db
    environment:
      POSTGRES_USER: pay-user
      POSTGRES_PASSWORD: pay-password
      POSTGRES_DB: payment-db
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    ports:
        - "5433:5432" # host port 5433 → container port 5432

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  # TODO: Uncomment when payment service is developed (currently using localhost for HMR)
  #payment-service:
  #  build: ./services/payment-service
  #  container_name: payment-service
  #  environment:
  #    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5432/payment-db
  #    - SPRING_DATASOURCE_USERNAME=pay-user
  #    - SPRING_DATASOURCE_PASSWORD=pay-password
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - postgres-payment

volumes:
  postgres-data:
  postgres-payment-data: