services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data: